---
- block:
  - name: Add CentOS-7 - OpenStack stein repo (disabled)
    become: true
    yum_repository:
      name: centos-openstack-stein
      description: CentOS-7 - OpenStack stein
      baseurl: http://mirror.centos.org/$contentdir/$releasever/cloud/$basearch/openstack-stein/
      enabled: false
      gpgcheck: false

  - name: Install OvS packages with CentOS-7 - OpenStack stein repo enabled
    become: true
    yum:
      name: openvswitch
      enablerepo: centos-openstack-stein,extras

  - name: Ensure OvS is running
    become: true
    systemd:
      name: openvswitch
      state: started
      enabled: true
      daemon_reload: true
