---

- name: Get Go Release
  become: true
  unarchive:
    src: https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Add the Go bin directory to the PATH environment variable for all users
  become: true
  copy:
    src: go-bin.sh
    dest: /etc/profile.d

- name: Set GOPATH for all users
  become: true
  copy:
    src: go-path.sh
    dest: /etc/profile.d
